/* =============================================================
   machine-data.js
   Loads machine data from machine-data.json (generated by
   scripts/process_csv.py) and exposes it as window.MACHINE_DATA.

   Falls back to an empty stub so the page still renders if the
   JSON hasn't been generated yet.
   ============================================================= */

(function (global) {
  'use strict';

  var SPEC_LIMIT = 8; // lower spec limit (g) — overridden by JSON value

  function emptyMachine(id) {
    return {
      label: 'B' + id + ' Machine',
      title: 'B' + id,
      date:  '—',
      specLimit: SPEC_LIMIT,
      excel: 'data/BOND PULL DATA IGN2932M75 B' + id + ' bonder.xlsx',
      dates: [],
      t1: [], t2: [], t3s: [], t3l: []
    };
  }

  function applyDefaults(data) {
    ['21','24','25','27'].forEach(function (id) {
      if (!data[id]) data[id] = emptyMachine(id);
      data[id].specLimit = data[id].specLimit || SPEC_LIMIT;
    });
    return data;
  }

  /* Fetch the generated JSON; fall back gracefully */
  fetch('data/machine-data.json')
    .then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    })
    .then(function (json) {
      global.MACHINE_DATA = applyDefaults(json);
      /* Notify dashboard.js that data is ready */
      document.dispatchEvent(new CustomEvent('machineDataReady'));
    })
    .catch(function (err) {
      console.warn('machine-data.json not found, using empty stubs.', err);
      global.MACHINE_DATA = applyDefaults({});
      document.dispatchEvent(new CustomEvent('machineDataReady'));
    });

})(window);
