/* =============================================================
   machine-data.js
   Fetches machine-data.json from the server (generated by
   scripts/process_csv.py) and exposes it as window.MACHINE_DATA.
   Falls back to empty stubs if the JSON is missing.
   ============================================================= */

(function (global) {
  'use strict';

  var SPEC_LIMIT = 8;

  function emptyMachine(id) {
    return {
      label: 'B' + id + ' Machine',
      title: 'B' + id,
      date:  '—',
      specLimit: SPEC_LIMIT,
      excel: 'data/BOND PULL DATA IGN2932M75 B' + id + ' bonder.xlsx',
      dates: [],
      t1: [], t2: [], t3s: [], t3l: []
    };
  }

  function applyDefaults(data) {
    ['21','24','25','27'].forEach(function (id) {
      if (!data[id]) data[id] = emptyMachine(id);
      data[id].specLimit = data[id].specLimit || SPEC_LIMIT;
    });
    return data;
  }

  /* Fetch fresh JSON every page load — no-cache headers ensure latest data */
  fetch('data/machine-data.json?t=' + Date.now())
    .then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    })
    .then(function (json) {
      global.MACHINE_DATA = applyDefaults(json);
      document.dispatchEvent(new CustomEvent('machineDataReady'));
    })
    .catch(function (err) {
      console.warn('machine-data.json not found, using empty stubs.', err);
      global.MACHINE_DATA = applyDefaults({});
      document.dispatchEvent(new CustomEvent('machineDataReady'));
    });

})(window);
